#!/bin/bash


##########
# mac OS #
##########
export BASH_SILENCE_DEPRECATION_WARNING=1

#######
# NVM #
#######
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
