#!/bin/bash

#######
# PHP #
#######
export PATH="/usr/local/php5/bin:/usr/local/bin:$PATH"

#################
# SONAR-SCANNER #
#################
export PATH="/Users/stavros.liaskos/sonar-scanner-4.2.0.1873-macosx/bin:$PATH"

############
# AWS-ADFS #
############
alias aws-export-assume-profile="~/developer/flaconi/aws-export-assume-profile/aws-export-assume-profile"
export PATH="/Users/stavros.liaskos/bin:$PATH"

##########
# mac OS #
##########
export BASH_SILENCE_DEPRECATION_WARNING=1

#######
# NVM #
#######
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

###########
# phpbrew #
###########
source /Users/stavros.liaskos/.phpbrew/bashrc
[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc

###########
# Go Lang #
###########
export GOPATH=~/go
