#!/bin/bash

########
# CONF #
########
MAGENTA=$(tput setaf 5)
LIME_YELLOW=$(tput setaf 190)
YELLOW=$(tput setaf 3)
WHITE=$(tput setaf 7)
CYAN=$(tput setaf 117)
WHITE=$(tput setaf 7)
RED=$(tput setaf 1)
RESET=$(tput sgr0)

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="________________________________________________________________________________\n${MAGENTA}\u: ${YELLOW}\w ${CYAN} on ${LIME_YELLOW} \$(parse_git_branch) ${RED}  \n\$ \[$RESET\]"
export PS2="| => "

#   Set Paths
export PATH="$PATH:/usr/local/bin/"
export PATH="/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

#   Set Default Editor (change 'Nano' to the editor of your choice)
export EDITOR=/usr/bin/nano

#   Set default blocksize for ls, df, du
#   from this: http://hints.macworld.com/comment.php?mode=view&cid=24491
export BLOCKSIZE=1k

